name: masari
version: 0.1.5.0
summary: "Masari: the secure, private, untraceable cryptocurrency https://getmasari.org"
description: |
    Masari is a private, secure, untraceable, decentralised digital currency.
    You are your bank, you control your funds, and nobody can trace your transfers
    unless you allow them to do so.
grade: devel
confinement: strict

apps:
    masarid:
        daemon: forking
        command: |
          masarid-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/masarid.conf
        plugs:
            - network
            - network-bind
    masari-wallet-rpc:
        command: |
          masari-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    masari-wallet-cli:
        command: |
          masari-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DUPNP_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libzmqpp-dev
            - libzmq3-dev
            - libsodium-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - libreadline6-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/masarid.conf: etc/masarid.conf
            contrib/snap/masarid-wrapper: bin/masarid-wrapper
        prime:
            - etc
            - bin
